generate:
	dart run build_runner build --delete-conflicting-outputs

watch: 
	dart run build_runner watch

fix-dry:
	dart fix --dry-run

fix:
	dart fix --apply

reverse:
	adb reverse tcp:8000 tcp:8000