name: rabt_mobile
description: "Rabt is a platform for volunteer networking for Palestine."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  flutter_dotenv: ^5.2.1
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  google_fonts: ^6.3.0
  image_picker: ^1.0.7
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.8
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.1
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/env/.env
    - assets/env/.env.local
    - assets/images/logo/
  
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo/logo.png"  # Your logo as foreground
  remove_alpha_ios: true  # Remove alpha channel for iOS App Store compliance